services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wedding_planner
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # app:
  #   build: .
  #   depends_on:
  #     - postgres
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL}
  #     NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
  #     NEXTAUTH_URL: ${NEXTAUTH_URL}
  #     NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
  #     SMTP_HOST: ${SMTP_HOST}
  #     SMTP_PORT: ${SMTP_PORT}
  #     SMTP_USER: ${SMTP_USER}
  #     SMTP_PASS: ${SMTP_PASS}
  #     SMTP_FROM_NAME: ${SMTP_FROM_NAME}
  #     SMTP_FROM_EMAIL: ${SMTP_FROM_EMAIL}
  #   ports:
  #     - "3000:3000"
