version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wedding_planner
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # migrate:
  #   build: .
  #   command: npx prisma migrate deploy
  #   depends_on:
  #     - db
  #   environment:
  #     DATABASE_URL: postgres://postgres:postgres@db:5432/wedding_planner

  # app:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
  #     - migrate
  #   environment:
  #     DATABASE_URL: postgres://postgres:postgres@db:5432/wedding_planner
  #     NEXTAUTH_SECRET: changeme
  #     NEXTAUTH_URL: http://localhost:3000
