import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Provider from "@/components/auth/Provider";
import { UserContextProvider } from "@/context/UserContext";

export const metadata: Metadata = {
  title: "Wedding Planner",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className="bg-brand-background text-brand-text"
      >
        <Provider>
          <UserContextProvider>
            {children}
          </UserContextProvider>
          <Toaster />
        </Provider>
      </body>
    </html>
  );
}
